### ISSUE TITLE
Debug SimpleCalculator

### ISSUE THREAD

**Issue by llmhyy** [llmhyy/programming_exercise#7]
The simple calculator program implements a basic calculator to evaluate a simple expression string.

The expression string may contain open ( and closing parentheses ), the plus + or minus sign -, non-negative integers and empty spaces.

However, there is a bug in the implemented program. It parses "(((1+((1+2)+(2-1))-(1-3))+1)+1)+1" into 6. However, the correct value should be 10.

**Comment by jelsaoverlandfrost** [comment]
I found that the problem is with "--", the program will take it as a "-", that's where the problem is.
(I think)

**Comment by llmhyy** [comment]
@jelsaoverlandfrost how do you debug the program? Can you fix this bug as well?

**Comment by jelsaoverlandfrost** [comment]
I used the traditional debug actually... Cuz got configuration problem with microbar lol... I think I should have fixed the bug already, by changing all the -- to +. But I am not sure if there will be more bugs afterwards though.

**Comment by jelsaoverlandfrost** [comment]
Wait... Did I push successfully?😂

**Comment by llmhyy** [comment]
@jelsaoverlandfrost  the push is successful but the fix seems to be an over simplified solution. :)

**Comment by jelsaoverlandfrost** [comment]
Ah really I tot I can solve the problem already hhhh nvm I go check again
